### ISSUE TITLE
String 2743 modified for consistency with String 5836

### ISSUE THREAD

**Issue by Goddesen** [OpenRCT2/Localisation#1068] opened 2017-04-23 14:47 UTC
Modified string from PR OpenRCT2/OpenRCT2#5397.

```
STR_2743    :Copy 'data/css17.dat' from your RCT1 installation to 'data/css50.dat' in your RCT2 installation, or make sure the path to RCT1 in the Miscellaneous tab is correct.
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES

**Comment by Nubbie** [comment] 2017-05-08 16:02
Duplicate off #1053 ?

**Comment by Gymnasiast** [comment] 2017-05-08 16:08
@Nubbie No. #1053 changed the text, #1068 changed backslashes to forward slashes.

**Closed** 2017-05-17 18:19 UTC
Labels: changed field
