### ISSUE TITLE
Use a translation platform

### ISSUE THREAD

**Issue by devnoname120** [OpenRCT2/Localisation#231] opened 2015-08-30 22:27 UTC
I think that translations should not be handled in a Github repository.
This makes it hard to maintain them (when a string is added to the source, each of the translation files needs to be modified), unpractical to contribute and ensure the quality of the translation (discussions hardly possible, no translation managers having the last word), etc.

This is why I believe that we should use a translation platform. Here are the most famous platforms amongst opensource projects. They are both free for this type of project, and feature an API to ease Github's integration.
- Crowdin: my favorite, works as expected
- Transifex: poorly documented (and slow) API

The main caveat would be the strings' format, for all I know. I doubt that it is supported by the aforementioned platforms.

**Comment by Gymnasiast** [comment] 2015-08-31 08:17
Closing as it's not a bug, and something to discuss on either the main repo or (preferably) the Gitter of the main repo. And it has been discussed earlier, with IntelOrca not being in favour of moving it.

**Closed by Gymnasiast** 2015-08-31 08:17 UTC
