### ISSUE TITLE
STR_5713

### ISSUE THREAD

**Issue by dlee13** [OpenRCT2/Localisation#504] opened 2016-04-04 03:47 UTC
`STR_5713    :Kick Player` has previously been unused.
OpenRCT2/OpenRCT2@ef4fc84 shows relocation of string id `STR_ACTION_KICK_PLAYER` from `5713` to `5659` without marking `STR_5713` as unused in the language files.

~~In OpenRCT2/OpenRCT2@774a2fe, I have changed it to
`STR_5713    :Can't remove default group `~~
Edit: My PR was closed. However, it should still be noted that `5713` and `5659` are duplicates. `5713` is unused.

**Comment by Wirlie** [comment] 2016-04-04 04:24
hum... te PR is open... I'm not sure, but I think that in this repository you only can make a new issue (for new and changed field) if the PR has been merged.

**Comment by Nubbiy** [comment] 2016-04-05 09:14
Agree with @Wirlie that you should wait, but nice observation about the string

**Comment by octaroot** [comment] 2016-04-06 12:54
The problem is that people who make changes to OpenRCT2 repo often forget to notify us, translators - in the past I've opened numerous issues in this repo, most of them did not originate from my commits to the OpenRCT2 repo ... it would be really nice to have some sort of a "tracking" system for the strings file, so that no new strings would come into the game unnoticed by translators (eg automatically creating new issues).

**Comment by Nubbiy** [comment] 2016-04-06 14:47
@octaroot I agree with you, the only way for translators to notice new changes if there is no new "Issues" on this site talking about the newly added strings are when you notice them in-game in English

**Comment by Gymnasiast** [comment] 2016-04-06 14:55
Most if the issues stem from the fact that we use Git repositories, rather than proper translation tools (such as Transifex).

**Comment by Wirlie** [comment] 2016-04-12 15:42
@Gymnasiast you can close this? Please. You have closed the PR OpenRCT2/OpenRCT2#3241 (this is implemented on #523 (OpenRCT2/OpenRCT2#3167))

**Comment by Gymnasiast** [comment] 2016-04-12 20:57
@Wirlie I only close PRs that are implemented in every active language. I will have to check first.

**Closed** 2016-05-06 07:03 UTC
